#!/usr/bin/env python
# -*- coding: utf-8 -*-

import getpass

username = raw_input("Enter Username: ")
passkey = getpass.getpass('Password: ')

from instabot import InstaBot

bot = InstaBot(login=username, password=passkey,
               like_per_day=50,
               comments_per_day=15,
               #tag_list=['followforfollow', 'bagpacking', 'solobagpacking', 'solotravel', 'travelgram', 'travel', 'summer', 'vsco', 'northeast', 'meghalaya', 'mizoram', 'nagaland', 'sikkim', 'manipur'],
               #tag_list=[ 'TagsForLikes ', 'TagsForLikesApp ', 'sky ', 'sun ', 'summer ', 'beach ', 'beautiful ', 'pretty ', 'sunset ', 'sunrise ', 'blue ', 'flowers ', 'night ', 'tree ', 'twilight ', 'clouds ', 'beauty ', 'light ', 'cloudporn ', 'flowers ', 'flower ', 'TagsForLikes ', 'petal ', 'petals ', 'nature ', 'beautiful ', 'love ', 'pretty ', 'plants ', 'blossom ', 'sopretty ', 'spring ', 'summer ', 'flowerstagram ', 'flowersofinstagram ', 'flowerstyles_gf ', 'flowerslovers ', 'flowerporn ', 'botanical ', 'floral ', 'florals ', 'insta_pick_blossom ', 'flowermagic ', 'instablooms ', 'bloom ', 'blooms ', 'botanical ', 'floweroftheday',  'photooftheday ', 'love ', 'green ', 'skylovers ', 'dusk ', 'weather ', 'day ', 'red ', 'iphonesia ', 'mothernature', 'love', 'TagsForLikes',  'TagsForLikesApp', 'TFLers', 'tweegram', 'photooftheday' ,'20likes' , 'smile', 'follow4follow', 'like4like', 'look', 'instalike', 'igers', 'picoftheday', 'food', 'instadaily', 'instafollow' 'followme', 'girl' ,'iphoneonly', 'instagood' ,'bestoftheday' , 'instacool' ,'instago' ,'all_shots' ,'follow', 'webstagram' ,'colorful','style' ,'swag',  'followforfollow', 'bagpacking', 'solobagpacking', 'solotravel', 'travelgram', 'travel', 'summer', 'vsco', 'instagood', 'mexico', 'lajolla', 'nyc', 'sandiego', 'nature', 'sunset', 'food', 'night', 'awesome', 'amazing', 'hiking', 'relaxing', 'travel', 'instatravel', 'travelgram', 'tourist', 'tourism', 'vacation', 'traveling', 'trip'],
               #tag_list = ['TagsForLikes', 'TagsForLikesApp', 'sky', 'sun', 'summer', 'beach', 'beautiful', 'pretty', 'sunset', 'sunrise', 'blue', 'flowers', 'night', 'tree', 'twilight', 'clouds', 'beauty', 'light', 'cloudporn', 'flowers', 'flower', 'TagsForLikes', 'petal', 'petals', 'nature', 'beautiful', 'love', 'pretty', 'plants', 'blossom', 'sopretty', 'spring', 'summer', 'flowerstagram', 'flowersofinstagram', 'flowerstyles_gf', 'flowerslovers', 'flowerporn', 'botanical', 'floral', 'florals', 'insta_pick_blossom', 'flowermagic', 'instablooms', 'bloom', 'blooms', 'botanical', 'floweroftheday', 'photooftheday', 'love', 'green', 'skylovers', 'dusk', 'weather', 'day', 'red', 'iphonesia', 'mothernature', 'love', 'TagsForLikes', 'TagsForLikesApp', 'TFLers', 'tweegram', 'photooftheday', '20likes', 'smile', 'follow4follow', 'like4like', 'look', 'instalike', 'igers', 'picoftheday', 'food', 'instadaily', 'instafollowfollowme', 'girl', 'iphoneonly', 'instagood', 'bestoftheday', 'instacool', 'instago', 'all_shots', 'follow', 'webstagram', 'colorful', 'style', 'swag', 'followforfollow', 'bagpacking', 'solobagpacking', 'solotravel', 'travelgram', 'travel', 'summer', 'vsco', 'instagood', 'mexico', 'lajolla', 'nyc', 'sandiego', 'nature', 'sunset', 'food', 'night', 'awesome', 'amazing', 'hiking', 'relaxing', 'travel', 'instatravel', 'travelgram', 'tourist', 'tourism', 'vacation', 'traveling', 'trip', 'fslc', 'followshoutoutlikecomment', 'TagsForLikesFSLC', 'TagsForLikesApp', 'follow', 'shoutout', 'followme', 'comment', 'TagsForLikes', 'f4f', 's4s', 'l4l', 'c4c', 'followback', 'shoutoutback', 'likeback', 'commentback', 'love', 'instagood', 'photooftheday', 'pleasefollow', 'pleaseshoutout', 'pleaselike', 'pleasecomment', 'teamfslcback', 'fslcback', 'follows', 'shoutouts', 'likes', 'comments', 'follow', 'f4f', 'followme', 'TagsForLikes', 'TFLers', 'TagsForLikesApp', 'followforfollow', 'follow4follow', 'teamfollowback', 'followher', 'followbackteam', 'followhim', 'followall', 'followalways', 'followback', 'me', 'love', 'pleasefollow', 'follows', 'follower', 'following', 'followme', 'like4like', 'TagsForLikes', 'TFLers', 'liker', 'likes', 'l4l', 'likes4likes', 'photooftheday', 'love', 'likeforlike', 'likesforlikes', 'liketeam', 'likeback', 'likebackteam', 'instagood', 'likeall', 'likealways', 'TagsForLikesApp', 'liking', 'comment', 'comment4comment', 'TagsForLikes', 'TFLers', 'c4c', 'commenter', 'comments', 'commenting', 'love', 'comments4comments', 'instagood', 'commentteam', 'commentback', 'commentbackteam', 'commentbelow', 'photooftheday', 'commentall', 'commentalways', 'pleasecomment'],
               
               # SEASONS
               tag_list = ['fall', 'seasons', 'orange', 'red', 'leaf', 'autumnweather', 'instagood', 'love', 'igers', 'leaves', 'tbt', 'tflers', 'colorful', 'cute', 'iphonesia', 'season', 'picoftheday', 'autumn', 'nature', 'me', 'foliage', 'instaautumn', 'instamood', 'girl', 'photooftheday', 'instafall', 'fallweather', 'tagblender', 'tweegram', 'falltime', 'leaves', 'season', 'cute', 'orange', 'tweegram', 'picoftheday', 'tbt', 'red', 'leaf', 'autumnweather', 'photooftheday', 'igers', 'girl', 'fallweather', 'instamood', 'nature', 'iphonesia', 'beautiful', 'fall', 'autumn', 'falltime', 'instafall', 'colorful', 'tagblender', 'instagood', 'foliage', 'instaautumn', 'seasons', 'tflers', 'love', 'clearsky', 'instamood', 'warm', 'fall', 'summertime', 'tflers', 'beautiful', 'clearskys', 'summer', 'summertimeshine', 'bluesky', 'hot', 'tagblender', 'me', 'weather', 'seasons', 'instasummer', 'instagood', 'sunshine', 'fun', 'summerweather', 'cute', 'sun', 'instafall', 'vacationtime', 'nature', 'sky', 'photooftheday', 'season', 'sunny', 'instawinter', 'instasnow', 'holidayseason', 'christmas', 'water', 'nature', 'winter', 'snow', 'cold', 'season', 'blizzard', 'holidays', 'rainyday', 'pouring', 'rain', 'ice', 'tagblender', 'seasons', 'cloud', 'raining', 'instagood', 'cloudporn', 'photooftheday', 'wintertime', 'snowing', 'rainydays', 'staywarm', 'cloudy', 'snowflakes', 'clouds'],
               max_like_for_one_tag=50,
               follow_per_day=50,
               #follow_time=5*60*60,
               follow_time=3,
               unfollow_per_day=0,
               unfollow_break_min=1,
               unfollow_break_max=1,
               log_mod=0)

bot.new_auto_mod()
